--Create Table ARTIST with Primary Key as ART_ID

CREATE TABLE ARTIST (
ART_ID INTEGER PRIMARY KEY,
ACTOR_NAME VARCHAR(20),
ACTRESS_NAME VARCHAR(20));

DESC ARTIST;

----------------------------

--Create Table DIRECTOR with Primary Key as DIR_ID

CREATE TABLE DIRECTOR(
DIR_ID INTEGER PRIMARY KEY,
DIR_NAME VARCHAR(20));

DESC DIRECTOR;

----------------------------

--Create Table MOVIE with Primary Key as MOV_ID and Foreign Key DIR_ID referring DIRECTOR table

CREATE TABLE MOVIE(
MOV_ID INTEGER PRIMARY KEY,
MOV_NAME VARCHAR(25),
MOV_YEAR INTEGER,
DIR_ID INTEGER,
FOREIGN KEY (DIR_ID) REFERENCES DIRECTOR(DIR_ID));

DESC MOVIE;

----------------------------

--Create Table MOVIE_CAST with Primary Key as MOV_ID and ACT_ID and Foreign Key ACT_ID and MOV_ID referring ACTOR and MOVIES tables respectively

CREATE TABLE CAST(
ART_ID INTEGER,
MOV_ID INTEGER,
PRIMARY KEY (ART_ID,MOV_ID),
FOREIGN KEY (ART_ID) REFERENCES ACTOR(ART_ID),
FOREIGN KEY (MOV_ID) REFERENCES MOVIES(MOV_ID));

DESC CAST;

----------------------------
