--INSERT records into ARTIST table

INSERT INTO ARTIST VALUES(101,'Aamir Khan', 'Anushka Sharma');
INSERT INTO ARTIST VALUES(102,'Zachary Levi', 'Mandy Moore');
INSERT INTO ARTIST VALUES(103,'John Travolta', 'Miley Cyrus');
INSERT INTO ARTIST VALUES(104,'Mohanlal', 'Meena');
INSERT INTO ARTIST VALUES(105,'Ryan Reynolds', 'Morena Baccarin');

SELECT * FROM ARTIST;

-----------------------------

--INSERT records into DIRECTOR table

INSERT INTO DIRECTOR VALUES(201,'Rajkumar Hirani');
INSERT INTO DIRECTOR VALUES(202,'Nathan Greno');
INSERT INTO DIRECTOR VALUES(203,'Bryon Howard');
INSERT INTO DIRECTOR VALUES(204,'Jeethu Joseph');
INSERT INTO DIRECTOR VALUES(205,'Tim Miller');

SELECT * FROM DIRECTOR;

------------------------------

--INSERT records into MOVIE table

INSERT INTO MOVIE VALUES(1001,'PK',2014,201);
INSERT INTO MOVIE VALUES(1002,'TANGLED',2010,202);
INSERT INTO MOVIE VALUES(1003,'SANJU',2018,201);
INSERT INTO MOVIE VALUES(1004,'DRISHYAM',2013,204);
INSERT INTO MOVIE VALUES(1005,'DEADPOOL',2016,205);

SELECT * FROM MOVIE;

-----------------------------



